language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r E:\Automation Testing\Python\radon-2.4.0\radon-2.4.0\requirements.txt
# command to run tests
script:
  - pytest
